version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "actions/*"
          - "github/*"
    labels:
      - "automated pr"
      - "dependencies"
      - "github actions"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    versioning-strategy: "increase"
    groups:
      actions:
        patterns:
          - "@actions/*"
      jest:
        patterns:
          - "@types/jest"
          - "jest"
          - "jest-*"
          - "ts-jest"
    labels:
      - "automated pr"
      - "dependencies"
      - "npm"
