name: "Problem Matcher for markdownlint"
description: "Sets up a problem matcher for markdownlint that's used to create annotations for violations"

inputs:
  action:
    description: "The action to take on the problem matcher (add or remove)"
    required: false
    default: add

runs:
  using: "node20"
  main: "dist/index.js"
