name: "Problem Matcher for markdownlint-cli2"

description: "Sets up a problem matcher for markdownlint-cli2 that's used to create annotations for violations"

author: "bsmth"

branding:
  icon: "command"
  color: "green"

inputs:
  action:
    description: "The action to take on the problem matcher (add or remove)"
    required: false
    default: add

runs:
  using: "node20"
  main: "dist/index.js"
