name: publish-release

on:
  push:
    branches:
      - main

jobs:
  publish:
    if: ${{ github.repository == 'bsmth/markdownlint-problem-matcher' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        with:
          persist-credentials: false
        uses: actions/checkout@v4

      - name: Release please
        uses: GoogleCloudPlatform/release-please-action@v4
        id: release
        with:
          release-type: node
          token: ${{ secrets.GITHUB_TOKEN }}
